"""Auto-maintain domain modules."""

from .infra.config import Settings, load_settings, load_watch_config
from .state.active_probe import ActiveUploadProbeDecision, ActiveUploadProbeState, decide_active_upload_probe
from .channel.channel_status import (
    CHANNEL_MAINTAIN,
    CHANNEL_UPLOAD,
    STAGE_DEFERRED,
    STAGE_DELETE,
    STAGE_DISABLE,
    STAGE_DONE,
    STAGE_ENABLE,
    STAGE_FAILED,
    STAGE_IDLE,
    STAGE_PENDING,
    STAGE_PENDING_FULL,
    STAGE_PENDING_INCREMENTAL,
    STAGE_PREPARE,
    STAGE_PROBE,
    STAGE_RETRY_WAIT,
    STAGE_RUNNING,
    STAGE_SCAN,
    STAGE_START_FAILED,
    STAGE_UPLOAD,
    STATE_FAILED,
    STATE_IDLE,
    STATE_PENDING,
    STATE_RUNNING,
    STATUS_FAILED,
    STATUS_RETRY,
    STATUS_SHUTDOWN,
    STATUS_SUCCESS,
)
from .channel.channel_commands import (
    build_maintain_command,
    build_upload_command,
    format_maintain_start_message,
    format_upload_start_message,
)
from .channel.channel_lifecycle import (
    MaintainProcessExitDecision,
    MaintainStartErrorDecision,
    UploadProcessExitDecision,
    UploadStartErrorDecision,
    decide_maintain_process_exit,
    decide_maintain_start_error,
    decide_upload_process_exit,
    decide_upload_start_error,
)
from .ui.dashboard import apply_panel_colors, fit_panel_line, panel_border_line
from .infra.locking import acquire_instance_lock, release_instance_lock
from .state.maintain_queue import (
    MaintainRuntimeState,
    MaintainQueueState,
    MaintainStartDecision,
    QueueMaintainResult,
    clear_maintain_queue_state,
    decide_maintain_start_scope,
    mark_maintain_runtime_retry,
    mark_maintain_retry,
    mark_maintain_success,
    mark_maintain_terminal_failure,
    merge_incremental_maintain_names,
    queue_maintain_request,
)
from .infra.output_pump import append_child_output_line, start_output_pump_thread
from .infra.process_runner import launch_child_command, start_channel_command, terminate_running_process
from .infra.process_output import build_child_process_env, decode_child_output_line, should_log_child_alert_line
from .ui.progress_parser import parse_progress_line
from .state.runtime_state import (
    build_maintain_queue_state,
    build_maintain_runtime_state,
    build_upload_queue_state,
    unpack_maintain_queue_state,
    unpack_maintain_runtime_state,
    unpack_upload_queue_state,
)
from .state.scope_files import write_scope_names
from .state.snapshots import (
    build_snapshot_file,
    build_snapshot_lines,
    compute_pending_upload_snapshot,
    compute_uploaded_baseline,
    extract_names_from_snapshot,
    read_snapshot_lines,
    write_snapshot_lines,
)
from .state.upload_queue import (
    UploadMergeResult,
    UploadQueueState,
    UploadStartDecision,
    clear_upload_queue_state,
    decide_upload_start,
    mark_upload_no_changes,
    mark_upload_no_pending_discovered,
    mark_upload_retry,
    mark_upload_success,
    mark_upload_terminal_failure,
    merge_pending_upload_snapshot,
)
from .state.upload_postprocess import (
    POST_UPLOAD_PENDING_REASON,
    UploadSuccessPostProcessResult,
    build_upload_success_postprocess,
)
from .infra.zip_intake import (
    compute_zip_signature,
    count_zip_files,
    extract_zip_with_bandizip,
    extract_zip_with_windows_builtin,
    inspect_zip_archives,
    list_zip_json_entries,
    list_zip_paths,
)

__all__ = [
    "Settings",
    "load_settings",
    "load_watch_config",
    "CHANNEL_UPLOAD",
    "CHANNEL_MAINTAIN",
    "STATE_IDLE",
    "STATE_PENDING",
    "STATE_RUNNING",
    "STATE_FAILED",
    "STATUS_SUCCESS",
    "STATUS_SHUTDOWN",
    "STATUS_RETRY",
    "STATUS_FAILED",
    "STAGE_IDLE",
    "STAGE_RUNNING",
    "STAGE_PENDING",
    "STAGE_PENDING_FULL",
    "STAGE_PENDING_INCREMENTAL",
    "STAGE_DEFERRED",
    "STAGE_START_FAILED",
    "STAGE_RETRY_WAIT",
    "STAGE_FAILED",
    "STAGE_SCAN",
    "STAGE_UPLOAD",
    "STAGE_DONE",
    "STAGE_PREPARE",
    "STAGE_PROBE",
    "STAGE_DELETE",
    "STAGE_DISABLE",
    "STAGE_ENABLE",
    "ActiveUploadProbeState",
    "ActiveUploadProbeDecision",
    "decide_active_upload_probe",
    "build_maintain_command",
    "build_upload_command",
    "format_maintain_start_message",
    "format_upload_start_message",
    "MaintainProcessExitDecision",
    "MaintainStartErrorDecision",
    "UploadProcessExitDecision",
    "UploadStartErrorDecision",
    "decide_maintain_process_exit",
    "decide_maintain_start_error",
    "decide_upload_process_exit",
    "decide_upload_start_error",
    "MaintainRuntimeState",
    "MaintainQueueState",
    "MaintainStartDecision",
    "QueueMaintainResult",
    "clear_maintain_queue_state",
    "decide_maintain_start_scope",
    "mark_maintain_runtime_retry",
    "mark_maintain_retry",
    "mark_maintain_success",
    "mark_maintain_terminal_failure",
    "queue_maintain_request",
    "merge_incremental_maintain_names",
    "acquire_instance_lock",
    "release_instance_lock",
    "append_child_output_line",
    "start_output_pump_thread",
    "launch_child_command",
    "start_channel_command",
    "terminate_running_process",
    "fit_panel_line",
    "panel_border_line",
    "apply_panel_colors",
    "build_child_process_env",
    "decode_child_output_line",
    "should_log_child_alert_line",
    "parse_progress_line",
    "build_upload_queue_state",
    "unpack_upload_queue_state",
    "build_maintain_queue_state",
    "unpack_maintain_queue_state",
    "build_maintain_runtime_state",
    "unpack_maintain_runtime_state",
    "write_scope_names",
    "list_zip_paths",
    "compute_zip_signature",
    "count_zip_files",
    "list_zip_json_entries",
    "extract_zip_with_windows_builtin",
    "extract_zip_with_bandizip",
    "inspect_zip_archives",
    "build_snapshot_lines",
    "write_snapshot_lines",
    "read_snapshot_lines",
    "build_snapshot_file",
    "UploadQueueState",
    "UploadStartDecision",
    "UploadMergeResult",
    "clear_upload_queue_state",
    "decide_upload_start",
    "mark_upload_no_changes",
    "mark_upload_no_pending_discovered",
    "mark_upload_retry",
    "mark_upload_success",
    "mark_upload_terminal_failure",
    "merge_pending_upload_snapshot",
    "POST_UPLOAD_PENDING_REASON",
    "UploadSuccessPostProcessResult",
    "build_upload_success_postprocess",
    "compute_pending_upload_snapshot",
    "compute_uploaded_baseline",
    "extract_names_from_snapshot",
]
